### ISSUE TITLE
启动游戏时崩溃

### ISSUE THREAD

**Issue by henryyuyhy** [zly2006/x-backup#1]
[crash-2024-11-03_21.58.52-client.txt](https://github.com/user-attachments/files/17610680/crash-2024-11-03_21.58.52-client.txt)
同时装载了textile backup，不知道是不是这个的问题

**Comment by zly2006** [comment]
https://modrinth.com/mod/x-backup/version/uqq9Rbfn

是和lithium冲突了，请帮忙测试此版本。

另外你是否也在用textile backup？是否有兴趣帮忙做一下磁盘占用和备份/回档速度相关的测试？

**Comment by henryyuyhy** [comment]
可以做与textile的对比，但考虑到我只有周末才玩的上mc可能需要3-4周才能出比较有意义的测试结果
以及作者大大更的好快啊
